---
title: "R Notebook"
output: html_notebook
---
libraries chunck
```{r echo=FALSE}
library(readxl)
library(tidyverse)
library(here)
```
load data
```{r}
birds_ship_data <- read_excel(here("clean_data/ship_birds.xlsx"))
```
most individual sightings 
```{r}
#Diomedea antipodensis / exulans PL3, Wandering albatross sensu lato PL3, 	DIOANTEXU PL3, 856
birds_ship_data %>%
  group_by(species_scientific_name, species_common_name, species_abbreviation) %>%
  filter(count == 1) %>%
  summarise(number_sightings = n()) %>%
  arrange(desc(number_sightings)) %>%
  head(1)
#Diomedea antipodensis / exulans PL3, Wandering albatross sensu lato PL3, 	DIOANTEXU PL3, 765
birds_ship_data %>%
  group_by(species_scientific_name, species_common_name, species_abbreviation) %>%
  filter(count == 1, accompanying_ocurrence == "N") %>%
  summarise(number_sightings = n()) %>%
  arrange(desc(number_sightings)) %>%
  head(1)
```
bird had the highest total count?
```{r}
#Puffinus tenuirostris	Short-tailed shearwater	PUFTEN	469320
birds_ship_data %>%
  group_by(species_scientific_name, species_common_name, species_abbreviation) %>%
  summarise(number_total_sightings = sum(count)) %>%
  arrange(desc(number_total_sightings)) %>%
  head(1)
```
birds highest total count in latitud -30
```{r}
#Puffinus pacificus	Wedge-tailed shearwater PUFPAC	855
birds_ship_data %>%
  group_by(species_scientific_name, species_common_name, species_abbreviation) %>%
  filter(lat > -30) %>% 
  summarise(number_total_sightings_30 = sum(count)) %>%
  arrange(desc(number_total_sightings_30))
  
```
How many different types of birds were only ever seen in groups of 1 
```{r}
#102
bird_view_one <- birds_ship_data %>%
  filter(count == 1) %>% 
bird_view_more <- birds_ship_data %>%
  filter(count >= 2)
bird_view_one %>%
  anti_join(bird_view_more, by = c("species_scientific_name",
   "species_common_name", "species_abbreviation")) %>%
  group_by(species_scientific_name, species_common_name, species_abbreviation) %>%
  summarise(real_species = n_distinct(species_common_name)) %>% 
  nrow()
```
penquin 93
```{r}
pattern = "[Pp]enguin"
birds_ship_data %>%
  filter(str_detect(species_common_name, pattern)) %>%
  summarise(total_penguin = sum(count))
  
```


