---
title: "R Notebook"
output: html_notebook
---

```{r include=FALSE}
library(tidyverse)
library(readr)
library(here)
```

Load data
```{r include=FALSE}
right_wing <- read_csv(here("clean_data/right_wing_clean.csv"))
```

1. Average RWA score for each gender
```{r}
right_wing %>%
  mutate_at("gender", as.character) %>%
  mutate(gender = recode(gender,
                            '0' = "no entry",
                            '1' = "male",
                            '2' = "female",
                            '3' = "other")) %>%
  group_by(gender) %>%
  summarise(average_score_per_gender = round(mean(score),2)) %>%
  filter(gender != "no entry")
              
  
```

2.  Average RWA score for left handed people vs. right handed people
```{r}
right_wing %>%
  mutate_at("hand", as.character) %>%
  mutate(hand = recode(hand,
                       '0' = "no entry",
                       '1' = "right",
                       '2' = "left",
                       '3' = "both")) %>%
  group_by(hand) %>%
  summarise(average_score_per_hand = round(mean(score),2)) %>%
  filter(!c(hand == "no entry" | hand == "both"))
```

3. Average family size for each type of childhood
```{r}
#The outliers in familisize don't affect the average because it is a lot data, so the mean isn't affecting for them
right_wing %>%
  filter(familysize <= 13)  %>%
  mutate_at("urban", as.character) %>%
  mutate(urban = recode(urban,
                        '0' = "no entry",
                        '1' = "rural",
                        '2' = "suburban",
                        '3' = "urban")) %>%
  group_by(urban) %>%
  summarise(average_familysize_chilhood = round(mean(familysize),0)) %>%
  filter(urban != "no entry")
```

4. Average time to take the test for each education level
```{r}
average_time_rwas_education_level <- right_wing %>%
  mutate_at("education", as.character) %>%
  mutate(education = recode(education,
                            '0' = "no entry",
                            '1' = "less than high school", 
                            '2' = "high school", 
                            '3' = "university degree", 
                            '4' = "graduate degree")) %>%
  group_by(education) %>%
  summarise(average_time = round(mean(time_a_rwas),0)) %>%
  filter(education != "no entry")

average_time_a_education_level <- right_wing %>%
  mutate_at("education", as.character) %>%
  mutate(education = recode(education,
                            '0' = "no entry",
                            '1' = "less than high school", 
                            '2' = "high school", 
                            '3' = "university degree", 
                            '4' = "graduate degree")) %>%
  group_by(education) %>%
  summarise(average_time = round(mean(total_time_s),0)) %>%
  filter(education != "no entry")

```

5. Plot average time to take the test for each education level
```{r}
ggplot(data = average_time_rwas_education_level, 
       mapping = aes(x = education,  y = average_time)) +
  geom_histogram(stat = "identity")

ggplot(data = average_time_a_education_level, 
       mapping = aes(x = education,  y = average_time)) +
  geom_histogram(stat = "identity")
```

6. Average RWA score for people aged
  
```{r}
interval_age <- c(18, 26, 41, 61)

right_wing <- right_wing %>%
  arrange(age) %>%
  mutate(group_age = findInterval(age, interval_age)) 

right_wing %>%
  mutate_at("group_age", as.character) %>%
  mutate(group_age = recode(group_age,
                        '0' = "under 18",
                        '1' = "18 - 25",
                        '2' = "26 - 40",
                        '3' = "41 - 60",
                        '4' = "over 60")) %>%
  group_by(group_age) %>%
  summarise(average_rwas_age = round(mean(score),2))
```

